"""empty message

Revision ID: 447d28587119
Revises: 
Create Date: 2020-11-30 10:32:26.008409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '447d28587119'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('sid', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=30), nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=40), nullable=True),
    sa.Column('total_rating', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('sid')
    )
    op.create_table('teachers',
    sa.Column('tid', sa.Integer(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=40), nullable=False),
    sa.Column('password', sa.VARCHAR(length=40), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=30), nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=40), nullable=True),
    sa.PrimaryKeyConstraint('tid')
    )
    op.create_table('ratings',
    sa.Column('rid', sa.Integer(), nullable=False),
    sa.Column('subject', sa.VARCHAR(length=30), nullable=True),
    sa.Column('svalue', sa.Integer(), nullable=True),
    sa.Column('sid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sid'], ['students.sid'], ),
    sa.PrimaryKeyConstraint('rid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ratings')
    op.drop_table('teachers')
    op.drop_table('students')
    # ### end Alembic commands ###
